# Generated by Django 4.1.3 on 2022-11-27 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90)),
                ('email', models.EmailField(max_length=254)),
                ('consulta', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PostGaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=90)),
                ('sub_titulo', models.CharField(max_length=90)),
                ('fecha', models.DateField()),
                ('texto', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PostHardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=90)),
                ('sub_titulo', models.CharField(max_length=90)),
                ('fecha', models.DateField()),
                ('texto', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PostNoticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=90)),
                ('sub_titulo', models.CharField(max_length=90)),
                ('fecha', models.DateField()),
                ('texto', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PostReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=90)),
                ('sub_titulo', models.CharField(max_length=90)),
                ('fecha', models.DateField()),
                ('texto', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PostSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=90)),
                ('sub_titulo', models.CharField(max_length=90)),
                ('fecha', models.DateField()),
                ('texto', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=90)),
                ('imagen', models.ImageField(upload_to='images/')),
                ('sub_titulo', models.CharField(max_length=90)),
                ('fecha', models.DateField()),
                ('categoria', models.CharField(choices=[('', 'Select Option'), ('Noticias', 'Noticias'), ('Reviews', 'Reviews'), ('Gaming', 'Gaming'), ('Sofrware', 'Sofrware'), ('Hardware', 'Hardware')], default=1, max_length=20)),
                ('texto', models.CharField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
