# Generated by Django 4.1.3 on 2022-12-13 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.CharField(choices=[('', 'Select Option'), ('Noticias', 'Noticias'), ('Reviews', 'Reviews'), ('Gaming', 'Gaming'), ('Software', 'Software'), ('Hardware', 'Hardware')], default=1, max_length=20),
        ),
    ]
