# Generated by Django 4.1.3 on 2024-03-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_delete_autor_alter_post_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='consulta',
        ),
        migrations.AddField(
            model_name='contacto',
            name='asunto',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacto',
            name='mensaje',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
