# Generated by Django 4.1.3 on 2022-11-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_post_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.CharField(choices=[('', 'Select Option'), ('Noticias', 'Noticias'), ('Reviews', 'Reviews'), ('Gaming', 'Gaming'), ('Sofrware', 'Sofrware'), ('Hardware', 'Hardware')], default=1, max_length=20),
        ),
    ]
